# Generated by Django 5.1.5 on 2025-02-27 11:23

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")],
                        default=1,
                        verbose_name="status",
                    ),
                ),
                (
                    "activate_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="keep empty for an immediate activation",
                        null=True,
                    ),
                ),
                (
                    "deactivate_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="keep empty for indefinite activation",
                        null=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("subject", models.CharField(max_length=255)),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("registration_success", "Registration Success"),
                            ("verification_pending", "Verification Pending"),
                            ("verification_done", "Verification Done"),
                            ("pnr_status", "PNR Status"),
                            ("seat_availability", "Seat Availability"),
                            ("train_status", "Train Status"),
                            ("password_reset", "Password Reset"),
                            ("password_reset_done", "Password Reset Done"),
                            ("password_forgot", "Password Forgot"),
                        ],
                        max_length=1024,
                    ),
                ),
                ("body", models.TextField()),
                ("is_html", models.BooleanField(default=False)),
                ("template", models.TextField()),
            ],
            options={
                "verbose_name": "Email Template",
                "verbose_name_plural": "Email Templates",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("is_sent", models.BooleanField(default=False)),
                (
                    "email_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="meri_rail.emailtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
            },
        ),
    ]
