# Generated by Django 5.1.6 on 2025-03-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meri_rail", "0003_requests"),
    ]

    operations = [
        migrations.AddField(
            model_name="requests",
            name="activate_date",
            field=models.DateTimeField(
                blank=True,
                help_text="keep empty for an immediate activation",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="requests",
            name="deactivate_date",
            field=models.DateTimeField(
                blank=True, help_text="keep empty for indefinite activation", null=True
            ),
        ),
        migrations.AddField(
            model_name="requests",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Inactive"), (1, "Active")],
                default=1,
                verbose_name="status",
            ),
        ),
    ]
