# Generated by Django 5.1.5 on 2025-01-30 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("code", models.CharField(max_length=8, unique=True)),
                ("name_hi", models.CharField(max_length=512)),
                ("district", models.CharField(blank=True, max_length=255, null=True)),
                ("state", models.CharField(blank=True, max_length=255, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("trains_count", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Station",
                "verbose_name_plural": "Stations",
            },
        ),
        migrations.CreateModel(
            name="Uttrence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "stations",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uttrences",
                        to="stations.uttrence",
                    ),
                ),
            ],
            options={
                "verbose_name": "Uttrence",
                "verbose_name_plural": "Uttrences",
            },
        ),
    ]
