# Generated by Django 5.1.5 on 2025-01-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="station",
            name="latitude",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="station",
            name="longitude",
            field=models.CharField(blank=True, null=True),
        ),
    ]
