# Generated by Django 5.1.5 on 2025-01-31 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="station",
            name="code",
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name="station",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="station",
            unique_together={("name", "code")},
        ),
    ]
