# Generated by Django 5.1.5 on 2025-01-30 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stations", "0002_alter_station_latitude_alter_station_longitude"),
    ]

    operations = [
        migrations.CreateModel(
            name="Utterance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "station",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="utterances",
                        to="stations.station",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utterance",
                "verbose_name_plural": "Utterances",
            },
        ),
        migrations.DeleteModel(
            name="Uttrence",
        ),
    ]
