# Generated by Django 5.1.5 on 2025-01-31 06:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stations", "0002_alter_station_code_alter_station_name_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="station",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="station",
            name="code",
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
