# Generated by Django 5.1.5 on 2025-01-30 12:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stations", "0003_utterance_delete_uttrence"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="utterance",
            unique_together={("name", "station")},
        ),
    ]
