# Generated by Django 5.1.5 on 2025-02-05 13:51

import django.db.models.deletion
import django_extensions.db.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stations", "0001_initial"),
        ("trains", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pnr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("pnr", models.BigIntegerField(unique=True)),
                ("date_of_journey", models.DateField()),
                (
                    "journey_class",
                    models.CharField(blank=True, max_length=8, null=True),
                ),
                ("number_of_passengers", models.IntegerField(blank=True, null=True)),
                (
                    "chart_status",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "cancel_status",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("booking_fare", models.IntegerField(blank=True, null=True)),
                ("ticket_fare", models.IntegerField(blank=True, null=True)),
                ("quota", models.CharField(blank=True, max_length=16, null=True)),
                ("vikalp_otp", models.CharField(blank=True, max_length=8, null=True)),
                ("booking_date", models.DateField(blank=True, null=True)),
                (
                    "mobile_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region="IN"
                    ),
                ),
                ("distance", models.IntegerField(blank=True, null=True)),
                (
                    "boarding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boarding_pnrs",
                        to="stations.station",
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destination_pnrs",
                        to="stations.station",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_pnrs",
                        to="stations.station",
                    ),
                ),
                (
                    "train",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pnrs",
                        to="trains.train",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pnr",
                "verbose_name_plural": "Pnr",
            },
        ),
        migrations.CreateModel(
            name="Passengers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_number", models.IntegerField()),
                ("quota", models.CharField(blank=True, max_length=16, null=True)),
                ("nationality", models.CharField(blank=True, max_length=8, null=True)),
                (
                    "waitlist_type",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                (
                    "booking_status",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                (
                    "booking_coach",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                (
                    "booking_berth",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                (
                    "booking_details",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "current_status",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                (
                    "current_coach",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                (
                    "current_berth",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                (
                    "current_details",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "pnr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passengers",
                        to="pnrs.pnr",
                    ),
                ),
            ],
            options={
                "verbose_name": "Passengers",
                "verbose_name_plural": "Passengers",
            },
        ),
    ]
