# Generated by Django 5.1.5 on 2025-02-27 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pnrs", "0001_initial"),
        ("stations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pnr",
            name="boarding",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boarding_pnrs",
                to="stations.station",
            ),
        ),
        migrations.AddField(
            model_name="pnr",
            name="destination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="destination_pnrs",
                to="stations.station",
            ),
        ),
    ]
