# Generated by Django 5.1.5 on 2025-02-14 05:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pnrs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passengers",
            name="quota",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TQ", "Tatkal Quota"),
                    ("LD", "Ladies Quota"),
                    ("DF", "Defence Quota"),
                    ("FT", "Foreign Tourist Quota"),
                    ("SS", "Lower Berth Quota"),
                    ("PT", "Premium Tatkal Quota"),
                    ("YU", "Yuva Quota"),
                    ("DP", "Duty Pass Quota"),
                    ("HP", "Handicapped Quota"),
                    ("PH", "Parliament House"),
                    ("GN", "General Quota"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pnr",
            name="quota",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TQ", "Tatkal Quota"),
                    ("LD", "Ladies Quota"),
                    ("DF", "Defence Quota"),
                    ("FT", "Foreign Tourist Quota"),
                    ("SS", "Lower Berth Quota"),
                    ("PT", "Premium Tatkal Quota"),
                    ("YU", "Yuva Quota"),
                    ("DP", "Duty Pass Quota"),
                    ("HP", "Handicapped Quota"),
                    ("PH", "Parliament House"),
                    ("GN", "General Quota"),
                ],
                max_length=16,
                null=True,
            ),
        ),
    ]
