# Generated by Django 5.1.5 on 2025-02-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pnrs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="passengers",
            options={"verbose_name": "Passengers", "verbose_name_plural": "Passengers"},
        ),
        migrations.AlterModelOptions(
            name="pnr",
            options={"verbose_name": "Pnr", "verbose_name_plural": "Pnr"},
        ),
        migrations.RemoveField(
            model_name="pnr",
            name="fare",
        ),
        migrations.AlterField(
            model_name="pnr",
            name="booking_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pnr",
            name="booking_fare",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pnr",
            name="cancel_status",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="pnr",
            name="chart_status",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="pnr",
            name="distance",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pnr",
            name="journey_class",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name="pnr",
            name="number_of_passengers",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pnr",
            name="quota",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="pnr",
            name="ticket_fare",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pnr",
            name="vikalp_otp",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
