# Generated by Django 5.1.5 on 2025-02-04 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pnrs", "0001_initial"),
        ("stations", "0001_initial"),
        ("trains", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pnr",
            name="boarding",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boarding_pnrs",
                to="stations.station",
            ),
        ),
        migrations.AddField(
            model_name="pnr",
            name="destination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="destination_pnrs",
                to="stations.station",
            ),
        ),
        migrations.AddField(
            model_name="pnr",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="source_pnrs",
                to="stations.station",
            ),
        ),
        migrations.AddField(
            model_name="pnr",
            name="train",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pnrs",
                to="trains.train",
            ),
        ),
        migrations.AddField(
            model_name="passengers",
            name="pnr",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="passengers",
                to="pnrs.pnr",
            ),
        ),
    ]
