# Generated by Django 5.1.5 on 2025-02-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pnrs", "0002_alter_passengers_options_alter_pnr_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pnr",
            name="pnr",
            field=models.BigIntegerField(unique=True),
        ),
    ]
