# Generated by Django 5.1.5 on 2025-02-27 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pnrs", "0002_initial"),
        ("stations", "0001_initial"),
        ("trains", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pnr",
            name="emailed_users",
            field=models.ManyToManyField(
                blank=True, related_name="emailed_pnrs", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="pnr",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="source_pnrs",
                to="stations.station",
            ),
        ),
        migrations.AddField(
            model_name="pnr",
            name="train",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pnrs",
                to="trains.train",
            ),
        ),
        migrations.AddField(
            model_name="pnr",
            name="users",
            field=models.ManyToManyField(
                blank=True, related_name="pnrs", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="passengers",
            name="pnr",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="passengers",
                to="pnrs.pnr",
            ),
        ),
    ]
