# Generated by Django 5.1.5 on 2025-02-25 04:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pnrs", "0003_pnr_users"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pnr",
            name="emailed_users",
            field=models.ManyToManyField(
                blank=True, related_name="emailed_pnrs", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="pnr",
            name="users",
            field=models.ManyToManyField(
                blank=True, related_name="pnrs", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
