# Generated by Django 5.1.5 on 2025-02-11 13:55

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stations", "0001_initial"),
        ("trains", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainAvailableClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "joruney_class",
                    models.CharField(
                        choices=[
                            ("1A", "First AC"),
                            ("2A", "Second AC"),
                            ("3A", "Third AC"),
                            ("3E", "Third AC Economy"),
                            ("2S", "Second Seating"),
                            ("SL", "Sleeper"),
                            ("EC", "Executive Class"),
                            ("EA", "Executive Anubhuti"),
                            ("CC", "AC Chair Car"),
                            ("FC", "First Class"),
                            ("VS", "Vista Dome Non AC"),
                            ("CH", "Chair Car High Capacity"),
                            ("SH", "Sleeper High Capacity"),
                            ("VC", "Vista Dome CC"),
                            ("EV", "Vista Dome AC"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "train",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="train_available_class",
                        to="trains.train",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrainBetweenStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "from_station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="train_between_station_from",
                        to="stations.station",
                    ),
                ),
                (
                    "to_station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="train_between_station_to",
                        to="stations.station",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trains between stations",
                "verbose_name_plural": "Trains between stations",
                "unique_together": {("from_station", "to_station")},
            },
        ),
        migrations.CreateModel(
            name="TrainsList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arrival_time", models.TimeField()),
                ("departure_time", models.TimeField()),
                ("distance", models.CharField(max_length=8)),
                ("duration", models.CharField(max_length=8)),
                (
                    "train_type",
                    models.CharField(
                        choices=[
                            ("EXP", "Express"),
                            ("RAJ", "Rajdhani"),
                            ("SUP", "Super"),
                            ("RLM", "Regular"),
                        ],
                        max_length=16,
                    ),
                ),
                ("on_monday", models.BooleanField(default=False)),
                ("on_tuesday", models.BooleanField(default=False)),
                ("on_wednesday", models.BooleanField(default=False)),
                ("on_thursday", models.BooleanField(default=False)),
                ("on_friday", models.BooleanField(default=False)),
                ("on_saturday", models.BooleanField(default=False)),
                ("on_sunday", models.BooleanField(default=False)),
                (
                    "train",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trains_between_station_train_list",
                        to="trains.train",
                    ),
                ),
                (
                    "train_between_station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trains_list",
                        to="trains_between_station.trainbetweenstation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trains List",
                "verbose_name_plural": "Trains List",
                "unique_together": {("train", "train_between_station")},
            },
        ),
    ]
