# Generated by Django 5.1.5 on 2025-02-27 11:23

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SeatAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("dt", models.DateField(verbose_name="Date")),
                ("available", models.CharField(max_length=64)),
                (
                    "quota",
                    models.CharField(
                        choices=[
                            ("TQ", "Tatkal Quota"),
                            ("LD", "Ladies Quota"),
                            ("DF", "Defence Quota"),
                            ("FT", "Foreign Tourist Quota"),
                            ("SS", "Lower Berth Quota"),
                            ("PT", "Premium Tatkal Quota"),
                            ("YU", "Yuva Quota"),
                            ("DP", "Duty Pass Quota"),
                            ("HP", "Handicapped Quota"),
                            ("PH", "Parliament House"),
                            ("GN", "General Quota"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "train_cls",
                    models.CharField(
                        choices=[
                            ("1A", "First AC"),
                            ("2A", "Second AC"),
                            ("3A", "Third AC"),
                            ("3E", "Third AC Economy"),
                            ("2S", "Second Seating"),
                            ("SL", "Sleeper"),
                            ("EC", "Executive Class"),
                            ("EA", "Executive Anubhuti"),
                            ("CC", "AC Chair Car"),
                            ("FC", "First Class"),
                            ("VS", "Vista Dome Non AC"),
                            ("CH", "Chair Car High Capacity"),
                            ("SH", "Sleeper High Capacity"),
                            ("VC", "Vista Dome CC"),
                            ("EV", "Vista Dome AC"),
                        ],
                        max_length=64,
                    ),
                ),
            ],
            options={
                "verbose_name": "Seat Availability",
                "verbose_name_plural": "Seats Availability",
            },
        ),
    ]
