# Generated by Django 5.1.5 on 2025-02-13 11:07

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("trains", "0002_alter_train_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeatAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("dt", models.DateField(verbose_name="Date")),
                ("available", models.CharField(max_length=64)),
                (
                    "train",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seats_availability",
                        to="trains.train",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seat Availability",
                "verbose_name_plural": "Seats Availability",
            },
        ),
    ]
