# Generated by Django 5.1.5 on 2025-02-27 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("seat_availability", "0001_initial"),
        ("stations", "0001_initial"),
        ("trains", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="seatavailability",
            name="from_station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="from_seats_availability",
                to="stations.station",
            ),
        ),
        migrations.AddField(
            model_name="seatavailability",
            name="to_station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to_seats_availability",
                to="stations.station",
            ),
        ),
        migrations.AddField(
            model_name="seatavailability",
            name="train",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seats_availability",
                to="trains.train",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="seatavailability",
            unique_together={("train", "dt", "quota", "train_cls")},
        ),
    ]
