# Generated by Django 5.1.5 on 2025-02-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seat_availability", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="seatavailability",
            name="quota",
            field=models.CharField(
                choices=[
                    ("TQ", "Tatkal Quota"),
                    ("LD", "Ladies Quota"),
                    ("DF", "Defence Quota"),
                    ("FT", "Foreign Tourist Quota"),
                    ("SS", "Lower Berth Quota"),
                    ("PT", "Premium Tatkal Quota"),
                    ("YU", "Yuva Quota"),
                    ("DP", "Duty Pass Quota"),
                    ("HP", "Handicapped Quota"),
                    ("PH", "Parliament House"),
                    ("GN", "General Quota"),
                ],
                default=1,
                max_length=64,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="seatavailability",
            name="train_cls",
            field=models.CharField(
                choices=[
                    ("1A", "First AC"),
                    ("2A", "Second AC"),
                    ("3A", "Third AC"),
                    ("3E", "Third AC Economy"),
                    ("2S", "Second Seating"),
                    ("SL", "Sleeper"),
                    ("EC", "Executive Class"),
                    ("EA", "Executive Anubhuti"),
                    ("CC", "AC Chair Car"),
                    ("FC", "First Class"),
                    ("VS", "Vista Dome Non AC"),
                    ("CH", "Chair Car High Capacity"),
                    ("SH", "Sleeper High Capacity"),
                    ("VC", "Vista Dome CC"),
                    ("EV", "Vista Dome AC"),
                ],
                default=1,
                max_length=64,
            ),
            preserve_default=False,
        ),
    ]
