# Generated by Django 5.1.5 on 2025-02-13 12:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("seat_availability", "0002_seatavailability_quota_seatavailability_train_cls"),
        ("trains", "0002_alter_train_options"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="seatavailability",
            unique_together={("train", "dt", "quota", "train_cls")},
        ),
    ]
