# Generated by Django 5.1.5 on 2025-02-14 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seat_availability", "0003_alter_seatavailability_unique_together"),
        ("stations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="seatavailability",
            name="from_station",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="from_seats_availability",
                to="stations.station",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="seatavailability",
            name="to_station",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to_seats_availability",
                to="stations.station",
            ),
            preserve_default=False,
        ),
    ]
