# Generated by Django 5.1.5 on 2025-02-24 09:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_googleoauth2token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_verified",
        ),
    ]
