# Generated by Django 5.1.5 on 2025-02-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_user_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="activity_status",
            field=models.BooleanField(
                choices=[(0, "Unverified"), (1, "Verified")],
                default=1,
                verbose_name="Activity Status",
            ),
        ),
    ]
