# Generated by Django 5.1.5 on 2025-02-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_activity_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="activity_status",
            field=models.BooleanField(
                choices=[(1, "Verified"), (0, "Unverified")],
                default=1,
                verbose_name="Activity Status",
            ),
        ),
    ]
