# Generated by Django 5.1.5 on 2025-02-05 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stations", "0001_initial"),
        ("trains", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("distance", models.CharField(max_length=16)),
                ("total_fare", models.CharField(max_length=16)),
                ("quota", models.CharField(max_length=16)),
                ("train_cls", models.CharField(max_length=8)),
                (
                    "from_station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fares_from_stations",
                        to="stations.station",
                    ),
                ),
                (
                    "to_station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fares_to_stations",
                        to="stations.station",
                    ),
                ),
                (
                    "train",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="trains.train"
                    ),
                ),
            ],
            options={
                "verbose_name": "Fare",
                "verbose_name_plural": "Fare",
                "unique_together": {
                    ("train", "from_station", "to_station", "quota", "train_cls")
                },
            },
        ),
        migrations.CreateModel(
            name="FareBreakDown",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_fare", models.CharField(max_length=16)),
                ("reservation_charge", models.CharField(max_length=16)),
                ("superfast_charge", models.CharField(max_length=16)),
                ("total_concession", models.CharField(max_length=16)),
                ("tatkal_fare", models.CharField(max_length=16)),
                ("gst_charge", models.CharField(max_length=16)),
                ("other_charge", models.CharField(max_length=16)),
                ("catering_charge", models.CharField(max_length=16)),
                ("dynamic_fare", models.CharField(max_length=16)),
                (
                    "fare",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fare_enquiry.fare",
                    ),
                ),
            ],
        ),
    ]
