# Generated by Django 5.1.5 on 2025-02-27 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("fare_enquiry", "0001_initial"),
        ("stations", "0001_initial"),
        ("trains", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fare",
            name="from_station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fares_from_stations",
                to="stations.station",
            ),
        ),
        migrations.AddField(
            model_name="fare",
            name="to_station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fares_to_stations",
                to="stations.station",
            ),
        ),
        migrations.AddField(
            model_name="fare",
            name="train",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="trains.train"
            ),
        ),
        migrations.AddField(
            model_name="farebreakdown",
            name="fare",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="breakdown",
                to="fare_enquiry.fare",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fare",
            unique_together={
                ("train", "from_station", "to_station", "quota", "train_cls")
            },
        ),
    ]
