# Generated by Django 5.1.6 on 2025-03-06 12:56

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stations", "0001_initial"),
        ("trains", "0002_trainclass_train_journey_class"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("arrival", models.DateTimeField()),
                ("departure", models.DateTimeField()),
                ("date", models.DateField()),
                ("delay", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_history",
                        to="stations.station",
                    ),
                ),
                (
                    "train",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_history",
                        to="trains.train",
                    ),
                ),
            ],
            options={
                "verbose_name": "Live History for %s at %s on %s",
                "verbose_name_plural": "Live History",
                "ordering": ["-date"],
                "unique_together": {("train", "station", "date")},
            },
        ),
        migrations.CreateModel(
            name="LiveStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("departed_time", models.DateTimeField()),
                ("delay", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "departed_station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_status_departed",
                        to="stations.station",
                    ),
                ),
                (
                    "train",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_statuses",
                        to="trains.train",
                    ),
                ),
                (
                    "upcoming_station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_status_upcoming",
                        to="stations.station",
                    ),
                ),
            ],
            options={
                "verbose_name": "Live Status for {self.train} on {self.date}",
                "verbose_name_plural": "Live Status",
                "ordering": ["-date"],
                "unique_together": {("train", "date")},
            },
        ),
    ]
