# Generated by Django 5.1.5 on 2025-03-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trains", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("1A", "First AC"),
                            ("2A", "Second AC"),
                            ("3A", "Third AC"),
                            ("3E", "Third AC Economy"),
                            ("2S", "Second Seating"),
                            ("SL", "Sleeper"),
                            ("EC", "Executive Class"),
                            ("EA", "Executive Anubhuti"),
                            ("CC", "AC Chair Car"),
                            ("FC", "First Class"),
                            ("VS", "Vista Dome Non AC"),
                            ("CH", "Chair Car High Capacity"),
                            ("SH", "Sleeper High Capacity"),
                            ("VC", "Vista Dome CC"),
                            ("EV", "Vista Dome AC"),
                        ],
                        max_length=32,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Quota",
                "verbose_name_plural": "Quota",
            },
        ),
        migrations.AddField(
            model_name="train",
            name="journey_class",
            field=models.ManyToManyField(
                blank=True, related_name="trains", to="trains.trainclass"
            ),
        ),
    ]
