# Generated by Django 5.1.5 on 2025-01-31 08:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trains", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="train",
            old_name="train_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="train",
            old_name="train_number",
            new_name="number",
        ),
    ]
