# Generated by Django 5.1.5 on 2025-01-31 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trains", "0002_rename_train_name_train_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="train",
            options={
                "ordering": ["number"],
                "verbose_name": "Train",
                "verbose_name_plural": "Trains",
            },
        ),
        migrations.AlterField(
            model_name="train",
            name="number",
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
