# Generated by Django 5.1.5 on 2025-01-31 10:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trains", "0004_route_schedule_traindetail_delete_traindetails"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="train",
            options={
                "ordering": ("number",),
                "verbose_name": "Train",
                "verbose_name_plural": "Trains",
            },
        ),
    ]
