# Generated by Django 5.1.5 on 2025-02-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trains", "0006_alter_schedule_friday_alter_schedule_monday_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="friday",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="monday",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="saturday",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="sunday",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="thursday",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="tuesday",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="wednesday",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
