# Generated by Django 5.1.5 on 2025-02-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trains", "0007_alter_schedule_friday_alter_schedule_monday_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="arrival",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
