# Generated by Django 5.1.5 on 2025-02-03 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trains", "0008_alter_route_arrival"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="train",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule",
                to="trains.train",
            ),
        ),
    ]
